name = "findraw-backend"
main = "src/index.js"
compatibility_date = "2026-08-07"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "FINDRAW_SESSION"
class_name = "FindrawSession"

[[durable_objects.bindings]]
name = "FINDRAW_ROOM"
class_name = "FindrawRoom"

[[durable_objects.bindings]]
name = "FINDRAW_COMMUNITY"
class_name = "FindrawCommunity"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["FindrawSession"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["FindrawRoom"]

[[migrations]]
tag = "v3"
new_sqlite_classes = ["FindrawCommunity"]

[vars]
FRONTEND_URL = "https://findraw.pages.dev"
TWITCH_REDIRECT_URI = "https://findraw-backend.bonsaii.workers.dev/auth/twitch/callback"
